import Head from 'next/head'

export default function Home() {
  return (
    <div className="">
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by cabir"/>
          <link rel="icon" href="/facicon.ico" />
        </Head>
        <h1 className='text-center'>Food Ordering</h1>
    </div>
 
  );
}
